"""Rewrite the generated settings table in docs/configuration.md from jev_browse/config.py (make docs-gen)."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from jev_browse import config  # noqa: E402

BEGIN, END = "<!-- settings:begin (generated by make docs-gen) -->", "<!-- settings:end -->"
path = ROOT / "docs" / "configuration.md"
text = path.read_text()
head, rest = text.split(BEGIN, 1)
tail = rest.split(END, 1)[1]
path.write_text(head + BEGIN + "\n" + config.markdown_table() + END + tail)
print(f"updated {path.relative_to(ROOT)}")
